name = "hono-drizzle"
main = "src/index.ts"
compatibility_date = "2024-12-28"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "KV"
id = "29f895e412984f18821c32ee88cbe733"
preview_id = "008345baa3074b8d949228ea498b1082"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "hono-drizzle"
database_id = "555434a4-0d93-4e4b-a48b-6cf800ec2bb6"
migrations_dir = "migrations"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1